---
- name: ensure docker is running
  service: 
    name: docker 
    state: restarted
  sudo: yes

- name: add discourse user
  user: name=discourse groups=sudo,admin

- git:
    repo: https://github.com/discourse/discourse_docker.git
    dest: '{{ discourse_location }}'
    update: no

- name: copy discourse configuration app.yml
  copy: src=app.yml dest={{ discourse_location }}/containers/app.yml owner=discourse group=sudo

- name: fix discourse permissions
  file: path={{ discourse_location }} owner=discourse group=discourse recurse=yes
  register: discourse_copied

- name: install requirements
  command: ansible-galaxy install -r ansible-discourse/requirements.yml
  args:
    chdir: "{{ git_location }}"
  become: true

- name: execute playbook
  command: ansible-playbook ansible-discourse/playbooks/main.yml
  args:
    chdir: "{{ git_location }}"
  become: true

- name: rebuild discourse
  command: ./launcher rebuild app
  args:
    chdir: "{{ discourse_location }}"
  ignore_errors: yes
  become: true
