---
- name: stop discourse
  command: ./launcher stop app
  args:
    chdir: "{{ discourse_location }}"
  ignore_errors: yes
  become: true

- name: start discourse
  command: ./launcher start app
  args:
    chdir: "{{ discourse_location }}"
  ignore_errors: yes
  become: true

- name: restart discourse
  command: ./launcher restart app
  args:
    chdir: "{{ discourse_location }}"
  ignore_errors: yes
  become: true

- name: rebuild discourse
  command: ./launcher rebuild app
  args:
    chdir: "{{ discourse_location }}"
  ignore_errors: yes
  become: true

- name: bootstrap discourse
  command: ./launcher bootstrap app
  args:
    chdir: "{{ discourse_location }}"
  become: true

